id: IE861FA3C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T09:21:43+00:00'
last_modified: '2022-06-10T09:55:47.797171+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03666
  title: སྡོམ་གསུམ་རྣམ་བཤད་ཐར་ལམ་གསལ་བའི་མེ་ལོང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    66A0:
      image_group_id: I00KG03743
      title: Volume 1 of sdom gsum rnam bzhad thar lam gsal ba'i me long
      total_pages: 264
      order: 1
      base_file: 66A0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
